services:
  - type: web
    name: cs2p2p-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        value: cs2marketplaceSecretKey789456123
      - key: CALLBACK_URL
        value: https://cs2p2p-api.onrender.com/api/auth/steam/return
      - key: API_URL
        value: https://cs2p2p-api.onrender.com
      - key: CLIENT_URL
        value: https://csp2p-1.onrender.com
      - key: MONGO_URI
        value: mongodb+srv://eminoviaslan:asqo-140@csgeorgia.2hjvj.mongodb.net/cs2marketplace?retryWrites=true&w=majority&appName=CSGEorgia
      - key: STEAM_API_KEY
        value: F754A63D38C9F63C247615D6F88D868C
